config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  post :paga_callback, :controller => "checkout", :action => "paga_callback"

  get :confirm_paga_payment, :controller => "checkout", :action => "confirm_paga_payment"

  post :paga_notification, :controller => "checkout", :action => "paga_notification"

  namespace :admin do
    resources :paga_transactions, :only => [:index] do
    	get :complete, :on => :member
    end
  end

end

app/controllers/spree/admin/paga_transactions_controller.rb
module Spree
  module Admin
    class PagaTransactionsController < ResourceController

      def index
        @paga_transactions = Spree::PagaTransaction.includes(:order, :user).page(params[:page])
      end

      def complete
        @order = @paga_transaction.order
        begin
          @paga_transaction.update_attributes(status: Spree::PagaTransaction::SUCCESSFUL)
          flash.now[:success] = "Order Completed"
        rescue
          flash.now[:error] = "Sorry order cannot be completed"
        end
      end
    end
  end
end

app/views/spree/admin/paga_transactions/complete.js.erb
// Instead of using flash to check success. we should check @paga_transaction status
<% if flash[:success] %>
	$('td#'+"<%= @paga_transaction.id%>").html("")
	$('td.status').html("<%=j(Spree::PagaTransaction::SUCCESSFUL)%>")
<% end %>
$('#wrapper').prepend("<%= j(render :partial => 'spree/shared/flash_messages', :locals => {:additional_class => flash[:success] ? 'success' : 'error'}) %>");

app/views/spree/admin/paga_transactions/index.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/configuration' %>
<% content_for :page_title do %>
  <h1><%= Spree.t("paga_transactions") %></h1>
<% end %>

<table class="index table table-striped table-hover">
  <thead data-hook="admin_paga_transactions_index_headers">
    <th><%= Spree.t("transaction_id") %></th>
    <th><%= Spree.t("transaction_date") %></th>
    <th><%= Spree.t("amount") %></th>
    <th><%= Spree.t("order#") %></th>
    <th><%= Spree.t("user") %></th>
    <th><%= Spree.t("status") %></th>
    <th><%= Spree.t("response_status") %></th>
    <th data-hook="admin_paga_transactions_index_header_actions">&nbsp;</th>
  </thead>
  <tbody>
    <% @paga_transactions.each do |transaction|%>
      <tr id="<%= dom_id transaction %>" data-hook="admin_trackers_index_rows">
        <td><%= transaction.transaction_id %></td>
        <td><%= transaction.created_at %></td>
        <td><%= Spree::Money.new(transaction.amount, { currency: transaction.currency }) %></td>
        <td><%= transaction.order.number %></td>
        <td><%= transaction.user ? transaction.user.email : "Guest User" %></td>
        <td class="status"><%= transaction.status %></td>
        <td><%= transaction.response_status %></td>
        <td id= "<%= transaction.id%>" >
          <%= link_to_if(transaction.success?, "") do %>
            <%= link_to(Spree.t("complete"), complete_admin_paga_transaction_path(transaction), :remote => true, :confirm => "Are you sure?") %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @paga_transactions %>

<script type="text/javascript">

</script>